Launching a python run
Wed Feb 12 00:33:00 UTC 2025
MyoSuite:> Registering Myo Envs
2025-02-12 00:33:44.563721: I external/xla/xla/pjrt/pjrt_c_api_client.cc:130] PjRtCApiClient created.
2025-02-12 00:33:52.407045: I external/xla/xla/service/llvm_ir/llvm_command_line_options.cc:50] XLA (re)initializing LLVM with options fingerprint: 16458742031601978301
num steps: 0, eval/episode_reward: -48.7042121887207
num steps: 5038080, eval/episode_reward: 785.845703125
num steps: 10076160, eval/episode_reward: 881.0906982421875
num steps: 15114240, eval/episode_reward: 908.520263671875
num steps: 20152320, eval/episode_reward: 918.2413330078125
time to jit: 0:03:05.735693
time to train: 0:13:44.286544
2025-02-12 00:52:19.611488: I external/xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'loop_gather_fusion_4', 4 bytes spill stores, 4 bytes spill loads

time to jit: 0:01:37.510069
2025-02-12 00:53:14.708800: I external/xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'loop_gather_fusion_4', 4 bytes spill stores, 4 bytes spill loads

--Return--
> /nfs/nhome/live/jheald/myosuite/myosuite/envs/myo/mjx/ArmReach.py(403)main()->None
-> breakpoint()
(Pdb) 
Traceback (most recent call last):
  File "/nfs/nhome/live/jheald/myosuite/myosuite/envs/myo/mjx/ArmReach.py", line 406, in <module>
    main()
  File "/nfs/nhome/live/jheald/myosuite/myosuite/envs/myo/mjx/ArmReach.py", line 403, in main
    breakpoint()
  File "/nfs/nhome/live/jheald/.conda/envs/infosyn2/lib/python3.10/bdb.py", line 94, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/nfs/nhome/live/jheald/.conda/envs/infosyn2/lib/python3.10/bdb.py", line 156, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
